_wandb:
    value:
        cli_version: 0.25.0
        e:
            6otdaaecjq2b39sqrketv3jogy8fwhok:
                codePath: birdclassification.py
                codePathLocal: birdclassification.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "11.7"
                disk:
                    /:
                        total: "488371122176"
                        used: "291385765888"
                email: emlhu@ucsc.edu
                executable: C:\Users\emily\AppData\Local\Programs\Python\Python312\python.exe
                git:
                    commit: c2e1375e82226e0e4efa0acccc651935c61907fa
                    remote: https://github.com/michaelUCSC/CMPM17finalProject.git
                gpu: NVIDIA GeForce GTX 1650 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650 Ti
                      uuid: GPU-563987d2-47c4-2655-44de-b072b114ad68
                host: MSI
                memory:
                    total: "8401506304"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\emily\Videos\homework\CMPM17_Code\final\cmpm17finalproject\birdclassification.py
                python: CPython 3.12.7
                root: C:\Users\emily\Videos\homework\CMPM17_Code\final\cmpm17finalproject
                startedAt: "2026-03-12T23:41:33.303654Z"
                writerId: 6otdaaecjq2b39sqrketv3jogy8fwhok
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
            "4": 3.12.7
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
